//
// Module TIMER_Vlog.Timer_tb.struct
//
// Created:
//          by - user.group (host.domain)
//          at - 11:46:33 04/12/2005
//
// Generated by Mentor Graphics' HDL Designer(TM) 2005.1
//

`resetall
`timescale 1ns/10ps
module Timer_tb;


// Internal Declarations



// Local declarations

// Internal signal declarations
wire       alarm;
wire       clk;
wire [9:0] d;
wire [3:0] high;
wire [3:0] low;
wire       reset;
wire       start;
wire       stop;


// Instances 
Timer I0( 
   .clk   (clk), 
   .d     (d), 
   .reset (reset), 
   .start (start), 
   .stop  (stop), 
   .alarm (alarm), 
   .high  (high), 
   .low   (low)
); 

Timer_tester I1( 
   .alarm (alarm), 
   .high  (high), 
   .low   (low), 
   .clk   (clk), 
   .d     (d), 
   .reset (reset), 
   .start (start), 
   .stop  (stop)
); 


endmodule // Timer_tb

