--
-- VHDL Entity UART.uart_tb.symbol
--
-- Created:
--          by - user.group (host.domain)
--          at - 13:04:23 27/02/2001
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.0
--
-- hds interface_start
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY uart_tb IS
-- Declarations

END uart_tb ;

-- hds interface_end
--
-- VHDL Architecture UART.uart_tb.struct
--
-- Created:
--          by - user.group (host.domain)
--          at - 13:04:23 27/02/2001
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.0
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY UART;

ARCHITECTURE struct OF uart_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL addr     : std_logic_vector(2 DOWNTO 0);    -- 3-bit address bus
   SIGNAL clk      : std_logic;    -- 10 MHz clock
   SIGNAL cs       : std_logic;    -- chip select
   SIGNAL data_in  : std_logic_vector(7 DOWNTO 0);    -- 8-bit data in bus from cpu
   SIGNAL data_out : std_logic_vector(7 DOWNTO 0);    -- 8-bit data out bus to cpu
   SIGNAL int      : std_logic;    -- interrupt(1)
   SIGNAL nrw      : std_logic;    -- read(0), write(1)
   SIGNAL rst      : std_logic;    -- reset(0)
   SIGNAL sin      : std_logic;    -- serial input
   SIGNAL sout     : std_logic;    -- serial output


   -- Component Declarations
   COMPONENT tester
   PORT (
      data_out : IN     std_logic_vector (7 DOWNTO 0);
      int      : IN     std_logic ;
      sout     : IN     std_logic ;
      addr     : OUT    std_logic_vector (2 DOWNTO 0);
      clk      : OUT    std_logic ;
      cs       : OUT    std_logic ;
      data_in  : OUT    std_logic_vector (7 DOWNTO 0);
      nrw      : OUT    std_logic ;
      rst      : OUT    std_logic ;
      sin      : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT uart_top
   PORT (
      -- 3-bit address bus
      addr     : IN     std_logic_vector (2 DOWNTO 0);
      clk      : IN     std_logic ; -- 10 MHz clock
      cs       : IN     std_logic ; -- chip select
      -- 8-bit data in bus from cpu
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      nrw      : IN     std_logic ; -- read(0), write(1)
      rst      : IN     std_logic ; -- reset(0)
      sin      : IN     std_logic ; -- serial input
      -- 8-bit data out bus to cpu
      data_out : OUT    std_logic_vector (7 DOWNTO 0);
      int      : OUT    std_logic ; -- interrupt (1)
      sout     : OUT    std_logic  -- serial output
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : tester USE ENTITY UART.tester;
   FOR ALL : uart_top USE ENTITY UART.uart_top;
   -- pragma synthesis_on


BEGIN
   -- Instance port mappings.
   I0 : tester
      PORT MAP (
         data_out => data_out,
         int      => int,
         sout     => sout,
         addr     => addr,
         clk      => clk,
         cs       => cs,
         data_in  => data_in,
         nrw      => nrw,
         rst      => rst,
         sin      => sin
      );
   I1 : uart_top
      PORT MAP (
         addr     => addr,
         clk      => clk,
         cs       => cs,
         data_in  => data_in,
         nrw      => nrw,
         rst      => rst,
         sin      => sin,
         data_out => data_out,
         int      => int,
         sout     => sout
      );

END struct;
