-- VHDL Entity Sequencer_vhd.accumulator.symbol
--
-- Created:
--          by - user.group (host.domain)
--          at - 10:55:47 04/12/2005
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.1
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY accumulator IS
   PORT( 
      clock : IN     std_logic;
      clr   : IN     std_logic;
      inc   : IN     std_logic;
      ip    : IN     std_logic_vector (7 DOWNTO 0);
      ld    : IN     std_logic;
      op    : BUFFER std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END accumulator ;

--
-- VHDL Architecture Sequencer_vhd.accumulator.flow
--
-- Created:
--          by - user.group (host.domain)
--          at - 10:55:47 04/12/2005
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.1
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE flow OF accumulator IS

BEGIN

   -----------------------------------------------------------------
   truth_process_proc : PROCESS (clock)
   -----------------------------------------------------------------
   BEGIN
      IF (clock'EVENT 
         AND clock = '1') THEN
         IF  (clr = '1') THEN
            -- Reset Actions
            op <= "00000000";
         ELSIF  (ld = '1') THEN
            op <= ip;
         ELSIF  (inc = '1') THEN
            op <= unsigned(op)+1;
         ELSE
            op <= op;
         END IF;
      END IF;
   END PROCESS truth_process_proc;


END flow;
