-- VHDL Entity Sequencer_vhd.fibgen_tb.symbol
--
-- Created:
--          by - user.group (host.domain)
--          at - 10:56:48 04/12/2005
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.1
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY fibgen_tb IS
-- Declarations

END fibgen_tb ;

--
-- VHDL Architecture Sequencer_vhd.fibgen_tb.struct
--
-- Created:
--          by - user.group (host.domain)
--          at - 10:56:48 04/12/2005
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.1
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

-- pragma synthesis_off
LIBRARY Sequencer_vhd;
-- pragma synthesis_on

ARCHITECTURE struct OF fibgen_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clock   : std_logic;
   SIGNAL monitor : std_logic_vector(7 DOWNTO 0);
   SIGNAL reset   : std_logic;


   -- Component Declarations
   COMPONENT fibgen
   PORT (
      clock  : IN     std_logic ;
      reset  : IN     std_logic ;
      fibout : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT fibgen_tester
   PORT (
      monitor : IN     std_logic_vector (7 DOWNTO 0);
      clock   : OUT    std_logic ;
      reset   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : fibgen USE ENTITY Sequencer_vhd.fibgen;
   FOR ALL : fibgen_tester USE ENTITY Sequencer_vhd.fibgen_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   UUT : fibgen
      PORT MAP (
         clock  => clock,
         reset  => reset,
         fibout => monitor
      );
   Checker : fibgen_tester
      PORT MAP (
         monitor => monitor,
         clock   => clock,
         reset   => reset
      );

END struct;
