//
// Module UART_V.serial_interface.struct
//
// Created:
//          by - user.group (host.domain)
//          at - 12:39:56 04/12/2005
//
// Generated by Mentor Graphics' HDL Designer(TM) 2005.1
//

`resetall
`timescale 1ns/10ps
module serial_interface( 
   clear_flags, 
   clk, 
   datin,            // 8-bit data in bus from cpu
   enable_write, 
   rst, 
   sample, 
   ser_if_select, 
   sin, 
   start_xmit, 
   xmitdt_en, 
   enable_rcv_clk, 
   enable_xmit_clk, 
   int, 
   ser_if_data, 
   sout
);


// Internal Declarations

input        clear_flags;
input        clk;
input  [7:0] datin;
input        enable_write;
input        rst;
input        sample;
input  [1:0] ser_if_select;
input        sin;
input        start_xmit;
input        xmitdt_en;
output       enable_rcv_clk;
output       enable_xmit_clk;
output       int;
output [7:0] ser_if_data;
output       sout;


wire        clear_flags;
wire        clk;
wire [7:0]  datin; // 8-bit data in bus from cpu
wire        enable_write;
wire        rst;
wire        sample;
wire [1:0]  ser_if_select;
wire        sin;
wire        start_xmit;
wire        xmitdt_en;
wire        enable_rcv_clk;
wire        enable_xmit_clk;
wire        int;
wire [7:0]  ser_if_data;
wire        sout;

// Local declarations

// Internal signal declarations
wire       done_rcving;
wire       done_xmitting;
wire [2:0] rcv_bit_cnt;
wire       rcving;
wire       read_bit;
wire [7:0] recvdt;
wire [7:0] status;
wire [7:0] xmitdt;
wire       xmitting;
wire [7:0] zeros;


// ModuleWare signal declarations(v1.5) for instance 'ser_out_mux' of 'mux'
reg [7:0] mw_ser_out_muxtemp_dout;

reg [7:0] xmitdt_reg, recvdt_reg;

// Instances 
status_registers U_1( 
   .clear_flags   (clear_flags), 
   .clk           (clk), 
   .done_rcving   (done_rcving), 
   .done_xmitting (done_xmitting), 
   .rcving        (rcving), 
   .rst           (rst), 
   .xmitting      (xmitting), 
   .int           (int), 
   .status        (status)
); 

xmit_rcv_control U_0( 
   .clk             (clk), 
   .rst             (rst), 
   .sample          (sample), 
   .sin             (sin), 
   .start_xmit      (start_xmit), 
   .xmitdt          (xmitdt), 
   .done_rcving     (done_rcving), 
   .done_xmitting   (done_xmitting), 
   .enable_rcv_clk  (enable_rcv_clk), 
   .enable_xmit_clk (enable_xmit_clk), 
   .rcv_bit_cnt     (rcv_bit_cnt), 
   .rcving          (rcving), 
   .read_bit        (read_bit), 
   .sout            (sout), 
   .xmitting        (xmitting)
); 

// HDL Embedded Block 1 convert
// Non hierarchical flowchart

/////////////////////////////////////////////////////////////////
// Flowchart conv
always @ (posedge clk or negedge rst)
begin : conv_flowchart_proc
   // Asynchronous Reset
   if (!rst) begin
      // Reset Actions
      xmitdt_reg <= 0;
      recvdt_reg <= 0;

   end
   else
   begin
      if (xmitdt_en  && enable_write) begin
         xmitdt_reg <= datin;
      end
      else if (read_bit) begin
         recvdt_reg[rcv_bit_cnt] <= sin;
      end

   end
end

// Concurrent statements
assign xmitdt = xmitdt_reg;
assign recvdt = recvdt_reg;


// ModuleWare code(v1.5) for instance 'zeros' of 'constval'
assign zeros = 8'd0;

// ModuleWare code(v1.5) for instance 'ser_out_mux' of 'mux'
always @(xmitdt or recvdt or status or zeros or ser_if_select)
begin : ser_out_muxcombo_proc
   case (ser_if_select)
      2'd0: mw_ser_out_muxtemp_dout = xmitdt;
      2'd1: mw_ser_out_muxtemp_dout = recvdt;
      2'd2: mw_ser_out_muxtemp_dout = status;
      2'd3: mw_ser_out_muxtemp_dout = zeros;
      default: mw_ser_out_muxtemp_dout = 8'bx;
   endcase
end
assign ser_if_data = mw_ser_out_muxtemp_dout;

endmodule // serial_interface

