-- VHDL Entity UART.uart_tb.symbol
--
-- Created:
--          by - user.group (host.domain)
--          at - 11:55:19 04/12/2005
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.1
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY uart_tb IS
-- Declarations

END uart_tb ;

--
-- VHDL Architecture UART.uart_tb.struct
--
-- Created:
--          by - user.group (host.domain)
--          at - 11:55:19 04/12/2005
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.1
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

-- pragma synthesis_off
LIBRARY UART;
-- pragma synthesis_on

ARCHITECTURE struct OF uart_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL addr   : std_logic_vector(2 DOWNTO 0);    -- 3-bit address
   SIGNAL clk    : std_logic;                       -- 10 MHz clock
   SIGNAL cs     : std_logic;                       -- chip select
   SIGNAL datin  : std_logic_vector(7 DOWNTO 0);    -- data from cpu
   SIGNAL datout : std_logic_vector(7 DOWNTO 0);    -- data to cpu
   SIGNAL int    : std_logic;                       -- interrupt(1)
   SIGNAL nrw    : std_logic;                       -- r(0), w(1)
   SIGNAL rst    : std_logic;                       -- reset(0)
   SIGNAL sin    : std_logic;                       -- serial input
   SIGNAL sout   : std_logic;                       -- serial output


   -- Component Declarations
   COMPONENT tester
   PORT (
      datout : IN     std_logic_vector (7 DOWNTO 0);
      int    : IN     std_logic ;
      sout   : IN     std_logic ;
      addr   : OUT    std_logic_vector (2 DOWNTO 0);
      clk    : OUT    std_logic ;
      cs     : OUT    std_logic ;
      datin  : OUT    std_logic_vector (7 DOWNTO 0);
      nrw    : OUT    std_logic ;
      rst    : OUT    std_logic ;
      sin    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT uart_top
   PORT (
      -- 3-bit address bus
      addr   : IN     std_logic_vector (2 DOWNTO 0);
      clk    : IN     std_logic ;                    -- 10 MHz clock
      cs     : IN     std_logic ;                    -- chip select
      datin  : IN     std_logic_vector (7 DOWNTO 0); -- data from cpu
      nrw    : IN     std_logic ;                    -- r(0), w(1)
      rst    : IN     std_logic ;                    -- reset(0)
      sin    : IN     std_logic ;                    -- serial input
      datout : OUT    std_logic_vector (7 DOWNTO 0); -- data TO cpu
      int    : OUT    std_logic ;                    -- interrupt (1)
      sout   : OUT    std_logic                      -- serial output
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : tester USE ENTITY UART.tester;
   FOR ALL : uart_top USE ENTITY UART.uart_top;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : tester
      PORT MAP (
         datout => datout,
         int    => int,
         sout   => sout,
         addr   => addr,
         clk    => clk,
         cs     => cs,
         datin  => datin,
         nrw    => nrw,
         rst    => rst,
         sin    => sin
      );
   U_1 : uart_top
      PORT MAP (
         addr   => addr,
         clk    => clk,
         cs     => cs,
         datin  => datin,
         nrw    => nrw,
         rst    => rst,
         sin    => sin,
         datout => datout,
         int    => int,
         sout   => sout
      );

END struct;
