//
// Module Sequencer_vlg.fibgen_tb.struct
//
// Created:
//          by - user.group (host.domain)
//          at - 11:05:12 04/12/2005
//
// Generated by Mentor Graphics' HDL Designer(TM) 2005.1
//

`resetall
`timescale 1ns/10ps
module fibgen_tb;


// Internal Declarations



// Local declarations

// Internal signal declarations
wire       clock;
wire [7:0] monitor;
wire       reset;


// Instances 
fibgen UUT( 
   .clock  (clock), 
   .reset  (reset), 
   .fibout (monitor)
); 

fibgen_tester Checker( 
   .monitor (monitor), 
   .clock   (clock), 
   .reset   (reset)
); 


endmodule // fibgen_tb

