//
// Module Sequencer_vlg.fibgen.struct
//
// Created:
//          by - user.group (host.domain)
//          at - 11:05:04 04/12/2005
//
// Generated by Mentor Graphics' HDL Designer(TM) 2005.1
//

`resetall
`timescale 1ns/10ps
module fibgen( 
   clock, 
   reset, 
   fibout
);


// Internal Declarations

input        clock;
input        reset;
output [7:0] fibout;


wire        clock;
wire        reset;
wire [7:0]  fibout;

// Local declarations

// Internal signal declarations
wire [7:0] A;
wire [7:0] B;
wire       clr;
wire       gnd;
wire       inc;
wire       ld_A_B;
wire       ld_sum;
wire [7:0] sum;


// Instances 
accumulator acc_A( 
   .clock (clock), 
   .clr   (clr), 
   .inc   (gnd), 
   .ip    (fibout), 
   .ld    (ld_A_B), 
   .op    (A)
); 

accumulator acc_B( 
   .clock (clock), 
   .clr   (clr), 
   .inc   (inc), 
   .ip    (A), 
   .ld    (ld_A_B), 
   .op    (B)
); 

accumulator acc_sum( 
   .clock (clock), 
   .clr   (clr), 
   .inc   (gnd), 
   .ip    (sum), 
   .ld    (ld_sum), 
   .op    (fibout)
); 

control FSM( 
   .clock  (clock), 
   .reset  (reset), 
   .clr    (clr), 
   .inc    (inc), 
   .ld_A_B (ld_A_B), 
   .ld_sum (ld_sum)
); 

// HDL Embedded Text Block 1 adder
assign sum = A + B ;
// HDL Embedded Text Block 2 ground
assign gnd = 0 ;

endmodule // fibgen

